version: '2.1'

orbs:
  node: circleci/node@4.5.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.3

    working_directory: ~/repo

    steps:
      - checkout
      - node/install-packages

      - run: npm run build-frontend
      - run: npm run build-backend

      # run tests!
      - run: npm run test:ci
      - run:
          name: Generate code coverage
          command: npm run cover
          when: always

      - store_artifacts:
          path: test/test-results.xml
          prefix: tests
      - store_artifacts:
          path: test/coverage
          prefix: coverage
      - store_test_results:
          path: test/test-results.xml
          prefix: tests
